// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laiyslvxxlvexwaeneda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhaXlzbHZ4eGx2ZXh3YWVuZWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxOTIwNjUsImV4cCI6MjA3NTc2ODA2NX0.PPWX9cJFBsS2-tcAs2gI_F8vHQHVcTHw9ErNSY-pxsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});