// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubjttptjigwbjwqyiwmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVianR0cHRqaWd3Ymp3cXlpd21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTI2NjgsImV4cCI6MjA3NjE4ODY2OH0.ZtCjm5IaMPRGoQpXu6L2iM7TzCPdGEL8iru2UQdpvLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});